### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by dssuthar6** [theofficialvkr/VKrTV#1]
checked in android and windows, it's not working. only keeps it loading at player's skin.

**Comment by theofficialvkr** [comment]
FIxed

**Comment by dssuthar6** [comment]
No brother, its not working. 
![image](https://user-images.githubusercontent.com/123798385/215336283-dd05f565-e770-46ef-b1f6-f6f58ac10488.png)
![image](https://user-images.githubusercontent.com/123798385/215336303-77869474-41c3-4e13-a362-ee606bfa5433.png)
